### ISSUE TITLE
Inputs are not checked when Name resolver is used

### ISSUE THREAD

**Issue by J-Christophe** [MizarWeb/Mizar#28]
### Description
Steps to reproduce the problem:
1. Go to Mars
2. Go to North pole
3. Enable 2D
4. Type 0.0 -30.0 in Name resolver

### Expected behavior
The camera does not move and an error is displayed

### Actual behavior
The camera moves

**Comment by ratamiez** [comment]
Message displayed : "Bad input parameters (coordinates out of extent)"
