### ISSUE TITLE
Order to display a cartographic layer

### ISSUE THREAD

**Issue by J-Christophe** [MizarWeb/Mizar#33]
## Description
As user, I want to display on the top level the last selected layer so that I can visualize it

## Actual behavior
The layers are loaded in the order where they are defined. It means that last defined layer is displayed at the top level when it is selected. However, when the last defined layer is selected and that I select the first layer, the first layer is displayed behind the last layer (thus, the first layer is not visible because hidden by the last layer).

# Expected behavior
When the last defined layer is selected and that I select the first layer, the first layer is displayed at the top level.

**Comment by ratamiez** [comment]
Please provide 2 geojson layer for sky with polygons inside, which overlap each other

**Comment by J-Christophe** [comment]
Here you are :
http://emars.univ-lyon1.fr/geoserver/EmarsGis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=EmarsGis:emars_hirise_dtm&maxFeatures=5000&outputFormat=application/json

http://emars.univ-lyon1.fr/geoserver/EmarsGis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=EmarsGis:emars_hirise&maxFeatures=5000&outputFormat=application/json
