### ISSUE TITLE
Make enable a WMS/WMTS from the FeaturePopup

### ISSUE THREAD

**Issue by J-Christophe** [MizarWeb/Mizar#37]
A GeoJson can contain a specific keyword that allows the GUI to display a specific icon on the FeaturePopup. When the use clicks on it, the WMS/WMTS is enabled. When the user click another time, the WMS/WMTS is disabled.

This feature is used to navigate in the full resolution in the image instead of using the quicklook

**Comment by ratamiez** [comment]
Popup, click on WMS.
Closing popup do not alter WMS loading.
Re-clicking popup -> WMS still checked.

Same as quicklook.
