### ISSUE TITLE
Hips not valid in Hips registry

### ISSUE THREAD

**Issue by ratamiez** [MizarWeb/Mizar#41]
Since proxy is configurable, we have many error message for hips, like this :

Hips layer The DENIS database (DENIS Consortium, 2005) (denis) not valid in Hips registry (http://axel.u-strasbg.fr/HiPSCatService/B/denis/denis).

The url http://axel.u-strasbg.fr/HiPSCatService/B/denis/denis is active, so we have to search for the origin of this error message.

**Comment by J-Christophe** [comment]
The Hips implementation uses the IVOA standard
http://www.ivoa.net/documents/HiPS/20170519/REC-HIPS-1.0-20170519.pdf. The
Hips version that corresponds to this standard is version 1.4.

The Hips from Denis database has been created with a version 1.0 (
http://axel.u-strasbg.fr/HiPSCatService/B/denis/denis/properties).

Two choices :
  - we wait CDS updates the HIPS
  - I add a special case for this version
